version: "3.9"
services:
    # image project
    laravel_10:
        build:
            args:
                user: anderson
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: blulang
        container_name: blulang-api
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        external_links:
          - mysql_57
        depends_on:
            - redis
            - queue
        networks:
            - uni_network
            - laravel-eti

    # nginx
    nginx:
        image: nginx:alpine
        container_name: blulang-nginx
        restart: unless-stopped
        ports:
            - 8180:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel-eti

    # db mysql
    # mysql:
    #     image: mysql:5.7.22
    #     restart: unless-stopped
    #     environment:
    #         MYSQL_DATABASE: ${DB_DATABASE}
    #         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    #         MYSQL_PASSWORD: ${DB_PASSWORD}
    #         MYSQL_USER: ${DB_USERNAME}
    #     volumes:
    #         - ./.docker/mysql/dbdata:/var/lib/mysql
    #     ports:
    #         - 3357:3306
    #     networks:
    #         - laravel-eti

    # queue
    queue:
        build:
            args:
                user: anderson
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        command: "php artisan queue:work"
        container_name: blulang-queue
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel-eti

    # redis
    redis:
        image: redis:latest
        container_name: blulang-redis
        networks:
            - laravel-eti

networks:
    laravel-eti:
        driver: bridge
    uni_network:
      external: true